In [2]:
import numpy as np
y=np.array([1,2,3,4,5])
print(y)
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x)
print(x[0,0])
print(x.ndim)
print(y[1:4])
print(x[1,1:3])
print(x.shape)


[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
2
[2 3 4]
[7 8]
(2, 5)


In [3]:
import numpy as np
x=np.array([])
for y in range (1,4):
    x=np.append (x,y)
print(x)

[1. 2. 3.]


In [4]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in range (2):
    for y in range (2):
        for z in range (2):
            print(arr[x,y,z])

1
2
3
4
5
6
7
8


In [5]:
from numpy import random
x=random.randint(100,size=(3,5))
print(x)
list=[]
for y in range(3):
    list=np.append(list,np.sort(x[y]))
list=list.reshape(3,5)
print(list)

[[26 33 95 40 18]
 [65 75 85 53 93]
 [50 41 16 77 47]]
[[18. 26. 33. 40. 95.]
 [53. 65. 75. 85. 93.]
 [16. 41. 47. 50. 77.]]


In [6]:
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in range(3):
    for y in range(x+1):
        print("0",end="")
    print(array3[x])
print("")
for x in range(3,0,-1):
    for y in range(x):
        print("0",end="")
    print(array3[x-1])
print("")
for x in range(3):
    for y in range(x+1):
        print("0",end="")
    print(" ",end="")
    for y in range(3):
        print(array3[x,y],end=" ")
    print("")

0[1 2 3]
00[4 5 6]
000[7 8 9]

000[7 8 9]
00[4 5 6]
0[1 2 3]

0 1 2 3 
00 4 5 6 
000 7 8 9 
